version: '3.9'

networks:
  eo:

services:
  postgis:
      image: postgis/postgis
      container_name: postgis
      volumes:
        - ./data/postgis:/var/lib/postgresql
      networks:
        - eo
      extra_hosts:
        - "host.docker.internal:host-gateway"
      environment:
        - POSTGRES_PASSWORD=123456
        - POSTGRES_USER=postgres
        - POSTGRES_DB=metadata_db
      ports:
        - "5432:5432"
      restart: on-failure
      healthcheck:
        test: "PGPASSWORD=123456 pg_isready -h 127.0.0.1 -U postgres -d metadata_db"